version: 2
jobs:
  unit_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Build Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_dev.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make lint
            make test
  release_docs:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Build Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_dev.txt
      - run:
          name: Deploy docs
          command: |
            . venv/bin/activate
            mkdocs gh-deploy --remote-name upstream --clean -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - unit_tests
      - release_docs:
          filters:
            branches:
              only: master
